
export type QuizQuestion = {
  question: string;
  options: string[];
  correctAnswerIndex: number;
};

export type LocalizedQuizData = {
    [key in 'en' | 'fr' | 'es' | 'mg']: QuizQuestion[];
}

export const staticQuizData: LocalizedQuizData = {
  en: [
    { question: "What is the capital of France?", options: ["Berlin", "Madrid", "Paris", "Rome"], correctAnswerIndex: 2 },
    { question: "Which planet is known as the Red Planet?", options: ["Earth", "Mars", "Jupiter", "Venus"], correctAnswerIndex: 1 },
    { question: "What is the largest mammal in the world?", options: ["Elephant", "Blue Whale", "Giraffe", "Great White Shark"], correctAnswerIndex: 1 },
    { question: "Who wrote 'Romeo and Juliet'?", options: ["Charles Dickens", "William Shakespeare", "Jane Austen", "Mark Twain"], correctAnswerIndex: 1 },
    { question: "What is the chemical symbol for water?", options: ["O2", "CO2", "H2O", "NaCl"], correctAnswerIndex: 2 },
    { question: "How many continents are there on Earth?", options: ["5", "6", "7", "8"], correctAnswerIndex: 2 },
    { question: "What is the hardest natural substance on Earth?", options: ["Gold", "Iron", "Diamond", "Platinum"], correctAnswerIndex: 2 },
    { question: "Which country is home to the kangaroo?", options: ["South Africa", "India", "Australia", "Brazil"], correctAnswerIndex: 2 },
    { question: "Who painted the Mona Lisa?", options: ["Vincent van Gogh", "Pablo Picasso", "Leonardo da Vinci", "Claude Monet"], correctAnswerIndex: 2 },
    { question: "What is the main ingredient in guacamole?", options: ["Tomato", "Avocado", "Onion", "Lime"], correctAnswerIndex: 1 },
    { question: "In which year did the Titanic sink?", options: ["1905", "1912", "1918", "1923"], correctAnswerIndex: 1 },
    { question: "What is the currency of Japan?", options: ["Yuan", "Won", "Yen", "Baht"], correctAnswerIndex: 2 },
    { question: "Which element has the atomic number 1?", options: ["Helium", "Oxygen", "Hydrogen", "Carbon"], correctAnswerIndex: 2 },
    { question: "Who was the first person to walk on the moon?", options: ["Buzz Aldrin", "Yuri Gagarin", "Michael Collins", "Neil Armstrong"], correctAnswerIndex: 3 },
    { question: "What is the tallest mountain in the world?", options: ["K2", "Mount Everest", "Kangchenjunga", "Lhotse"], correctAnswerIndex: 1 },
    { question: "What is the primary language spoken in Brazil?", options: ["Spanish", "Portuguese", "English", "French"], correctAnswerIndex: 1 },
    { question: "Which is the largest ocean on Earth?", options: ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "Pacific Ocean"], correctAnswerIndex: 3 },
    { question: "What is the square root of 64?", options: ["6", "7", "8", "9"], correctAnswerIndex: 2 },
    { question: "Who is the author of the Harry Potter series?", options: ["J.R.R. Tolkien", "George R.R. Martin", "J.K. Rowling", "C.S. Lewis"], correctAnswerIndex: 2 },
    { question: "What is the name of the galaxy our solar system is in?", options: ["Andromeda", "Triangulum", "Whirlpool", "Milky Way"], correctAnswerIndex: 3 },
    { question: "How many players are on a standard soccer team on the field?", options: ["9", "10", "11", "12"], correctAnswerIndex: 2 },
    { question: "What gas do plants absorb from the atmosphere?", options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"], correctAnswerIndex: 1 },
    { question: "Which artist cut off his own ear?", options: ["Pablo Picasso", "Salvador Dalí", "Vincent van Gogh", "Claude Monet"], correctAnswerIndex: 2 },
    { question: "What is the capital of Canada?", options: ["Toronto", "Vancouver", "Montreal", "Ottawa"], correctAnswerIndex: 3 },
    { question: "Which is the longest river in the world?", options: ["Amazon River", "Nile River", "Yangtze River", "Mississippi River"], correctAnswerIndex: 1 },
    { question: "What does 'CPU' stand for?", options: ["Central Processing Unit", "Computer Personal Unit", "Central Processor Unit", "Control Processing Unit"], correctAnswerIndex: 0 },
    { question: "In what year did World War II end?", options: ["1942", "1945", "1950", "1939"], correctAnswerIndex: 1 },
    { question: "What is the largest desert in the world?", options: ["Sahara Desert", "Arabian Desert", "Gobi Desert", "Antarctic Polar Desert"], correctAnswerIndex: 3 },
    { question: "Who invented the telephone?", options: ["Thomas Edison", "Alexander Graham Bell", "Nikola Tesla", "Guglielmo Marconi"], correctAnswerIndex: 1 },
    { question: "What is the chemical symbol for gold?", options: ["Ag", "Au", "Pb", "Fe"], correctAnswerIndex: 1 },
    { question: "How many bones are in the adult human body?", options: ["206", "212", "198", "220"], correctAnswerIndex: 0 },
    { question: "Which country is known as the Land of the Rising Sun?", options: ["China", "South Korea", "Japan", "Thailand"], correctAnswerIndex: 2 },
    { question: "What is the main component of Earth's atmosphere?", options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Argon"], correctAnswerIndex: 2 },
    { question: "Who discovered penicillin?", options: ["Marie Curie", "Louis Pasteur", "Alexander Fleming", "Robert Koch"], correctAnswerIndex: 2 },
    { question: "What is the capital of Australia?", options: ["Sydney", "Melbourne", "Canberra", "Perth"], correctAnswerIndex: 2 },
    { question: "How many planets are in our solar system?", options: ["7", "8", "9", "10"], correctAnswerIndex: 1 },
    { question: "What is the fastest land animal?", options: ["Lion", "Pronghorn", "Cheetah", "Wildebeest"], correctAnswerIndex: 2 },
    { question: "What is the boiling point of water in Celsius?", options: ["90°C", "100°C", "110°C", "120°C"], correctAnswerIndex: 1 },
    { question: "Who wrote 'The Great Gatsby'?", options: ["F. Scott Fitzgerald", "Ernest Hemingway", "William Faulkner", "John Steinbeck"], correctAnswerIndex: 0 },
    { question: "What is the currency of the United Kingdom?", options: ["Euro", "Dollar", "Pound Sterling", "Franc"], correctAnswerIndex: 2 },
    { question: "Which is the smallest continent?", options: ["Europe", "South America", "Antarctica", "Australia"], correctAnswerIndex: 3 },
    { question: "What is the official language of Egypt?", options: ["English", "French", "Arabic", "Egyptian"], correctAnswerIndex: 2 },
    { question: "Who was the first President of the United States?", options: ["Thomas Jefferson", "Abraham Lincoln", "George Washington", "John Adams"], correctAnswerIndex: 2 },
    { question: "Which is the most spoken language in the world?", options: ["Spanish", "English", "Mandarin Chinese", "Hindi"], correctAnswerIndex: 2 },
    { question: "What is the largest organ in the human body?", options: ["Liver", "Brain", "Heart", "Skin"], correctAnswerIndex: 3 },
    { question: "What do bees produce?", options: ["Syrup", "Honey", "Nectar", "Pollen"], correctAnswerIndex: 1 },
    { question: "Which famous scientist developed the theory of relativity?", options: ["Isaac Newton", "Galileo Galilei", "Albert Einstein", "Stephen Hawking"], correctAnswerIndex: 2 },
    { question: "How many sides does a hexagon have?", options: ["5", "6", "7", "8"], correctAnswerIndex: 1 },
    { question: "Which ocean is the Bermuda Triangle located in?", options: ["Pacific", "Indian", "Arctic", "Atlantic"], correctAnswerIndex: 3 },
    { question: "What is the main character in the 'Lord of the Rings' series?", options: ["Harry Potter", "Frodo Baggins", "Luke Skywalker", "Jon Snow"], correctAnswerIndex: 1 },
    { question: "What is the capital of Italy?", options: ["Venice", "Florence", "Milan", "Rome"], correctAnswerIndex: 3 },
    { question: "What is the chemical formula for table salt?", options: ["H2O", "CO2", "NaCl", "C6H12O6"], correctAnswerIndex: 2 },
    { question: "Which animal is known as the 'King of the Jungle'?", options: ["Tiger", "Elephant", "Lion", "Gorilla"], correctAnswerIndex: 2 },
    { question: "What is the term for a word that reads the same forwards and backwards?", options: ["Synonym", "Antonym", "Palindrome", "Anagram"], correctAnswerIndex: 2 },
    { question: "How many colors are in a rainbow?", options: ["5", "6", "7", "8"], correctAnswerIndex: 2 },
    { question: "In which country would you find the Great Wall?", options: ["India", "Egypt", "China", "Peru"], correctAnswerIndex: 2 },
    { question: "What is the name of the wizard in 'The Hobbit'?", options: ["Dumbledore", "Gandalf", "Merlin", "Saruman"], correctAnswerIndex: 1 },
    { question: "What type of fish is Nemo in the movie 'Finding Nemo'?", options: ["Goldfish", "Clownfish", "Angelfish", "Guppy"], correctAnswerIndex: 1 },
    { question: "What is the largest country in the world by area?", options: ["Canada", "China", "USA", "Russia"], correctAnswerIndex: 3 },
    { question: "What is the name of the toy cowboy in 'Toy Story'?", options: ["Buzz Lightyear", "Woody", "Mr. Potato Head", "Slinky Dog"], correctAnswerIndex: 1 },
    { question: "What is the main gas that makes up the Sun?", options: ["Oxygen", "Helium", "Hydrogen", "Carbon"], correctAnswerIndex: 2 },
    { question: "Who is the Greek god of the sea?", options: ["Zeus", "Hades", "Poseidon", "Apollo"], correctAnswerIndex: 2 },
    { question: "Which city is famous for its leaning tower?", options: ["Rome", "Pisa", "Florence", "Venice"], correctAnswerIndex: 1 },
    { question: "What is the capital of Russia?", options: ["Saint Petersburg", "Moscow", "Kazan", "Novosibirsk"], correctAnswerIndex: 1 },
    { question: "How many strings does a violin have?", options: ["4", "5", "6", "7"], correctAnswerIndex: 0 },
    { question: "What is the national sport of Canada?", options: ["Hockey and Lacrosse", "Baseball", "Soccer", "Curling"], correctAnswerIndex: 0 },
    { question: "What is a group of lions called?", options: ["A herd", "A pack", "A pride", "A flock"], correctAnswerIndex: 2 },
    { question: "Which continent is Spain in?", options: ["Asia", "Africa", "Europe", "South America"], correctAnswerIndex: 2 },
    { question: "What is the currency of India?", options: ["Rupee", "Yen", "Dollar", "Euro"], correctAnswerIndex: 0 },
    { question: "What is the smallest prime number?", options: ["0", "1", "2", "3"], correctAnswerIndex: 2 },
    { question: "Who painted 'Starry Night'?", options: ["Claude Monet", "Vincent van Gogh", "Pablo Picasso", "Salvador Dalí"], correctAnswerIndex: 1 },
    { question: "What is the capital of Argentina?", options: ["Santiago", "Lima", "Buenos Aires", "Bogotá"], correctAnswerIndex: 2 },
    { question: "What is the chemical symbol for Silver?", options: ["Si", "Sv", "Ag", "Sl"], correctAnswerIndex: 2 },
    { question: "Who is credited with inventing the light bulb?", options: ["Nikola Tesla", "Thomas Edison", "Alexander Graham Bell", "James Watt"], correctAnswerIndex: 1 },
    { question: "Which planet is closest to the Sun?", options: ["Venus", "Mars", "Mercury", "Earth"], correctAnswerIndex: 2 },
    { question: "In what country is the Suez Canal located?", options: ["Panama", "Egypt", "Turkey", "Greece"], correctAnswerIndex: 1 },
    { question: "What is the hardest known mineral?", options: ["Quartz", "Topaz", "Corundum", "Diamond"], correctAnswerIndex: 3 },
    { question: "How many sides does an octagon have?", options: ["6", "8", "10", "12"], correctAnswerIndex: 1 },
    { question: "Who wrote 'The Odyssey'?", options: ["Homer", "Virgil", "Sophocles", "Plato"], correctAnswerIndex: 0 },
    { question: "What is the world's largest island?", options: ["Greenland", "New Guinea", "Borneo", "Madagascar"], correctAnswerIndex: 0 },
    { question: "What is the capital of South Korea?", options: ["Pyongyang", "Seoul", "Busan", "Incheon"], correctAnswerIndex: 1 },
    { question: "What gas is most abundant in the Earth's atmosphere?", options: ["Oxygen", "Hydrogen", "Nitrogen", "Carbon Dioxide"], correctAnswerIndex: 2 },
    { question: "Who was the first woman to fly solo across the Atlantic Ocean?", options: ["Bessie Coleman", "Harriet Quimby", "Amelia Earhart", "Jacqueline Cochran"], correctAnswerIndex: 2 },
    { question: "What is the fear of spiders called?", options: ["Agoraphobia", "Acrophobia", "Claustrophobia", "Arachnophobia"], correctAnswerIndex: 3 },
    { question: "What is the capital of New Zealand?", options: ["Auckland", "Wellington", "Christchurch", "Hamilton"], correctAnswerIndex: 1 },
    { question: "Who directed the movie 'Jaws'?", options: ["George Lucas", "Alfred Hitchcock", "Steven Spielberg", "Martin Scorsese"], correctAnswerIndex: 2 },
    { question: "What is the main ingredient in a traditional Japanese miso soup?", options: ["Tofu", "Seaweed", "Miso paste", "Dashi"], correctAnswerIndex: 2 },
    { question: "How many hearts does an octopus have?", options: ["1", "2", "3", "4"], correctAnswerIndex: 2 },
    { question: "What is the name of the river that flows through London?", options: ["Seine", "Thames", "Danube", "Tiber"], correctAnswerIndex: 1 },
    { question: "Who wrote 'Pride and Prejudice'?", options: ["Emily Brontë", "Jane Austen", "Mary Shelley", "George Eliot"], correctAnswerIndex: 1 },
    { question: "What is the largest bone in the human body?", options: ["Humerus", "Tibia", "Femur", "Fibula"], correctAnswerIndex: 2 },
    { question: "What is the smallest country in the world?", options: ["Monaco", "Nauru", "Tuvalu", "Vatican City"], correctAnswerIndex: 3 },
    { question: "Which is the only mammal capable of true flight?", options: ["Flying squirrel", "Bat", "Sugar glider", "Colugo"], correctAnswerIndex: 1 },
    { question: "What is the currency of Switzerland?", options: ["Euro", "Swiss Franc", "Dollar", "Pound"], correctAnswerIndex: 1 },
    { question: "Who discovered gravity?", options: ["Albert Einstein", "Galileo Galilei", "Isaac Newton", "Nikola Tesla"], correctAnswerIndex: 2 },
    { question: "What is the capital of Spain?", options: ["Barcelona", "Lisbon", "Madrid", "Seville"], correctAnswerIndex: 2 },
    { question: "What element does 'Fe' represent on the periodic table?", options: ["Fluorine", "Iron", "Gold", "Lead"], correctAnswerIndex: 1 },
    { question: "Which is the world's longest continental mountain range?", options: ["Himalayas", "Rockies", "Andes", "Alps"], correctAnswerIndex: 2 },
    { question: "Who painted the ceiling of the Sistine Chapel?", options: ["Raphael", "Donatello", "Leonardo da Vinci", "Michelangelo"], correctAnswerIndex: 3 },
    { question: "What is the chemical formula for Ozone?", options: ["O", "O2", "O3", "O4"], correctAnswerIndex: 2 },
    { question: "What sport is played at Wimbledon?", options: ["Golf", "Tennis", "Cricket", "Rugby"], correctAnswerIndex: 1 },
    { question: "What is the largest moon in the Solar System?", options: ["Titan", "Ganymede", "Callisto", "Io"], correctAnswerIndex: 1 },
    { question: "What is the capital of Egypt?", options: ["Alexandria", "Giza", "Cairo", "Luxor"], correctAnswerIndex: 2 },
    { question: "What is the name of the dog in 'The Simpsons'?", options: ["Santa's Little Helper", "Snoopy", "Brian", "Scooby-Doo"], correctAnswerIndex: 0 }
  ],
  fr: [
    { question: "Quelle est la capitale de la France ?", options: ["Berlin", "Madrid", "Paris", "Rome"], correctAnswerIndex: 2 },
    { question: "Quelle planète est connue comme la Planète Rouge ?", options: ["Terre", "Mars", "Jupiter", "Vénus"], correctAnswerIndex: 1 },
    { question: "Quel est le plus grand mammifère du monde ?", options: ["Éléphant", "Baleine bleue", "Girafe", "Grand requin blanc"], correctAnswerIndex: 1 },
    { question: "Qui a écrit 'Roméo et Juliette' ?", options: ["Charles Dickens", "William Shakespeare", "Jane Austen", "Mark Twain"], correctAnswerIndex: 1 },
    { question: "Quel est le symbole chimique de l'eau ?", options: ["O2", "CO2", "H2O", "NaCl"], correctAnswerIndex: 2 },
    { question: "Combien de continents y a-t-il sur Terre ?", options: ["5", "6", "7", "8"], correctAnswerIndex: 2 },
    { question: "Quelle est la substance naturelle la plus dure sur Terre ?", options: ["Or", "Fer", "Diamant", "Platine"], correctAnswerIndex: 2 },
    { question: "Quel pays abrite le kangourou ?", options: ["Afrique du Sud", "Inde", "Australie", "Brésil"], correctAnswerIndex: 2 },
    { question: "Qui a peint la Joconde ?", options: ["Vincent van Gogh", "Pablo Picasso", "Léonard de Vinci", "Claude Monet"], correctAnswerIndex: 2 },
    { question: "Quel est l'ingrédient principal du guacamole ?", options: ["Tomate", "Avocat", "Oignon", "Citron vert"], correctAnswerIndex: 1 },
    { question: "En quelle année le Titanic a-t-il coulé ?", options: ["1905", "1912", "1918", "1923"], correctAnswerIndex: 1 },
    { question: "Quelle est la monnaie du Japon ?", options: ["Yuan", "Won", "Yen", "Baht"], correctAnswerIndex: 2 },
    { question: "Quel élément a le numéro atomique 1 ?", options: ["Hélium", "Oxygène", "Hydrogène", "Carbone"], correctAnswerIndex: 2 },
    { question: "Qui a été la première personne à marcher sur la lune ?", options: ["Buzz Aldrin", "Youri Gagarine", "Michael Collins", "Neil Armstrong"], correctAnswerIndex: 3 },
    { question: "Quelle est la plus haute montagne du monde ?", options: ["K2", "Mont Everest", "Kangchenjunga", "Lhotse"], correctAnswerIndex: 1 },
    { question: "Quelle est la langue principale parlée au Brésil ?", options: ["Espagnol", "Portugais", "Anglais", "Français"], correctAnswerIndex: 1 },
    { question: "Quel est le plus grand océan de la Terre ?", options: ["Océan Atlantique", "Océan Indien", "Océan Arctique", "Océan Pacifique"], correctAnswerIndex: 3 },
    { question: "Quelle est la racine carrée de 64 ?", options: ["6", "7", "8", "9"], correctAnswerIndex: 2 },
    { question: "Qui est l'auteur de la série Harry Potter ?", options: ["J.R.R. Tolkien", "George R.R. Martin", "J.K. Rowling", "C.S. Lewis"], correctAnswerIndex: 2 },
    { question: "Quel est le nom de la galaxie de notre système solaire ?", options: ["Andromède", "Triangle", "Tourbillon", "Voie lactée"], correctAnswerIndex: 3 },
    { question: "Combien de joueurs y a-t-il dans une équipe de football standard sur le terrain ?", options: ["9", "10", "11", "12"], correctAnswerIndex: 2 },
    { question: "Quel gaz les plantes absorbent-elles de l'atmosphère ?", options: ["Oxygène", "Dioxyde de carbone", "Azote", "Hydrogène"], correctAnswerIndex: 1 },
    { question: "Quel artiste s'est coupé l'oreille ?", options: ["Pablo Picasso", "Salvador Dalí", "Vincent van Gogh", "Claude Monet"], correctAnswerIndex: 2 },
    { question: "Quelle est la capitale du Canada ?", options: ["Toronto", "Vancouver", "Montréal", "Ottawa"], correctAnswerIndex: 3 },
    { question: "Quel est le plus long fleuve du monde ?", options: ["Amazone", "Nil", "Yangtsé", "Mississippi"], correctAnswerIndex: 1 },
    { question: "Que signifie 'CPU' ?", options: ["Central Processing Unit", "Computer Personal Unit", "Central Processor Unit", "Control Processing Unit"], correctAnswerIndex: 0 },
    { question: "En quelle année la Seconde Guerre mondiale s'est-elle terminée ?", options: ["1942", "1945", "1950", "1939"], correctAnswerIndex: 1 },
    { question: "Quel est le plus grand désert du monde ?", options: ["Désert du Sahara", "Désert d'Arabie", "Désert de Gobi", "Désert polaire antarctique"], correctAnswerIndex: 3 },
    { question: "Qui a inventé le téléphone ?", options: ["Thomas Edison", "Alexander Graham Bell", "Nikola Tesla", "Guglielmo Marconi"], correctAnswerIndex: 1 },
    { question: "Quel est le symbole chimique de l'or ?", options: ["Ag", "Au", "Pb", "Fe"], correctAnswerIndex: 1 },
    { question: "Combien d'os y a-t-il dans le corps humain adulte ?", options: ["206", "212", "198", "220"], correctAnswerIndex: 0 },
    { question: "Quel pays est connu comme le Pays du Soleil Levant ?", options: ["Chine", "Corée du Sud", "Japon", "Thaïlande"], correctAnswerIndex: 2 },
    { question: "Quel est le principal composant de l'atmosphère terrestre ?", options: ["Oxygène", "Dioxyde de carbone", "Azote", "Argon"], correctAnswerIndex: 2 },
    { question: "Qui a découvert la pénicilline ?", options: ["Marie Curie", "Louis Pasteur", "Alexander Fleming", "Robert Koch"], correctAnswerIndex: 2 },
    { question: "Quelle est la capitale de l'Australie ?", options: ["Sydney", "Melbourne", "Canberra", "Perth"], correctAnswerIndex: 2 },
    { question: "Combien de planètes y a-t-il dans notre système solaire ?", options: ["7", "8", "9", "10"], correctAnswerIndex: 1 },
    { question: "Quel est l'animal terrestre le plus rapide ?", options: ["Lion", "Antilocapre", "Guépard", "Gnou"], correctAnswerIndex: 2 },
    { question: "Quel est le point d'ébullition de l'eau en Celsius ?", options: ["90°C", "100°C", "110°C", "120°C"], correctAnswerIndex: 1 },
    { question: "Qui a écrit 'Gatsby le Magnifique' ?", options: ["F. Scott Fitzgerald", "Ernest Hemingway", "William Faulkner", "John Steinbeck"], correctAnswerIndex: 0 },
    { question: "Quelle est la monnaie du Royaume-Uni ?", options: ["Euro", "Dollar", "Livre sterling", "Franc"], correctAnswerIndex: 2 },
    { question: "Quel est le plus petit continent ?", options: ["Europe", "Amérique du Sud", "Antarctique", "Australie"], correctAnswerIndex: 3 },
    { question: "Quelle est la langue officielle de l'Égypte ?", options: ["Anglais", "Français", "Arabe", "Égyptien"], correctAnswerIndex: 2 },
    { question: "Qui était le premier président des États-Unis ?", options: ["Thomas Jefferson", "Abraham Lincoln", "George Washington", "John Adams"], correctAnswerIndex: 2 },
    { question: "Quelle est la langue la plus parlée au monde ?", options: ["Espagnol", "Anglais", "Chinois mandarin", "Hindi"], correctAnswerIndex: 2 },
    { question: "Quel est le plus grand organe du corps humain ?", options: ["Foie", "Cerveau", "Cœur", "Peau"], correctAnswerIndex: 3 },
    { question: "Que produisent les abeilles ?", options: ["Sirop", "Miel", "Nectar", "Pollen"], correctAnswerIndex: 1 },
    { question: "Quel célèbre scientifique a développé la théorie de la relativité ?", options: ["Isaac Newton", "Galilée", "Albert Einstein", "Stephen Hawking"], correctAnswerIndex: 2 },
    { question: "Combien de côtés a un hexagone ?", options: ["5", "6", "7", "8"], correctAnswerIndex: 1 },
    { question: "Dans quel océan se trouve le Triangle des Bermudes ?", options: ["Pacifique", "Indien", "Arctique", "Atlantique"], correctAnswerIndex: 3 },
    { question: "Quel est le personnage principal de la série 'Le Seigneur des Anneaux' ?", options: ["Harry Potter", "Frodon Sacquet", "Luke Skywalker", "Jon Snow"], correctAnswerIndex: 1 },
    { question: "Quelle est la capitale de l'Italie ?", options: ["Venise", "Florence", "Milan", "Rome"], correctAnswerIndex: 3 },
    { question: "Quelle est la formule chimique du sel de table ?", options: ["H2O", "CO2", "NaCl", "C6H12O6"], correctAnswerIndex: 2 },
    { question: "Quel animal est connu comme le 'Roi de la Jungle' ?", options: ["Tigre", "Éléphant", "Lion", "Gorille"], correctAnswerIndex: 2 },
    { question: "Quel est le terme pour un mot qui se lit de la même manière à l'endroit et à l'envers ?", options: ["Synonyme", "Antonyme", "Palindrome", "Anagramme"], correctAnswerIndex: 2 },
    { question: "Combien de couleurs y a-t-il dans un arc-en-ciel ?", options: ["5", "6", "7", "8"], correctAnswerIndex: 2 },
    { question: "Dans quel pays trouveriez-vous la Grande Muraille ?", options: ["Inde", "Égypte", "Chine", "Pérou"], correctAnswerIndex: 2 },
    { question: "Quel est le nom du magicien dans 'Le Hobbit' ?", options: ["Dumbledore", "Gandalf", "Merlin", "Saroumane"], correctAnswerIndex: 1 },
    { question: "Quel type de poisson est Némo dans le film 'Le Monde de Nemo' ?", options: ["Poisson rouge", "Poisson-clown", "Scalaire", "Guppy"], correctAnswerIndex: 1 },
    { question: "Quel est le plus grand pays du monde par sa superficie ?", options: ["Canada", "Chine", "États-Unis", "Russie"], correctAnswerIndex: 3 },
    { question: "Quel est le nom du cow-boy jouet dans 'Toy Story' ?", options: ["Buzz l'Éclair", "Woody", "M. Patate", "Slinky Dog"], correctAnswerIndex: 1 },
    { question: "Quel est le gaz principal qui compose le Soleil ?", options: ["Oxygène", "Hélium", "Hydrogène", "Carbone"], correctAnswerIndex: 2 },
    { question: "Qui est le dieu grec de la mer ?", options: ["Zeus", "Hadès", "Poséidon", "Apollon"], correctAnswerIndex: 2 },
    { question: "Quelle ville est célèbre pour sa tour penchée ?", options: ["Rome", "Pise", "Florence", "Venise"], correctAnswerIndex: 1 },
    { question: "Quelle est la capitale de la Russie ?", options: ["Saint-Pétersbourg", "Moscou", "Kazan", "Novossibirsk"], correctAnswerIndex: 1 },
    { question: "Combien de cordes un violon a-t-il ?", options: ["4", "5", "6", "7"], correctAnswerIndex: 0 },
    { question: "Quel est le sport national du Canada ?", options: ["Hockey et Crosse", "Baseball", "Soccer", "Curling"], correctAnswerIndex: 0 },
    { question: "Comment appelle-t-on un groupe de lions ?", options: ["Un troupeau", "Une meute", "Une fierté", "Un vol"], correctAnswerIndex: 2 },
    { question: "Dans quel continent se trouve l'Espagne ?", options: ["Asie", "Afrique", "Europe", "Amérique du Sud"], correctAnswerIndex: 2 },
    { question: "Quelle est la monnaie de l'Inde ?", options: ["Roupie", "Yen", "Dollar", "Euro"], correctAnswerIndex: 0 },
    { question: "Quel est le plus petit nombre premier ?", options: ["0", "1", "2", "3"], correctAnswerIndex: 2 },
    { question: "Qui a peint 'La Nuit étoilée' ?", options: ["Claude Monet", "Vincent van Gogh", "Pablo Picasso", "Salvador Dalí"], correctAnswerIndex: 1 },
    { question: "Quelle est la capitale de l'Argentine ?", options: ["Santiago", "Lima", "Buenos Aires", "Bogotá"], correctAnswerIndex: 2 },
    { question: "Quel est le symbole chimique de l'Argent ?", options: ["Si", "Sv", "Ag", "Sl"], correctAnswerIndex: 2 },
    { question: "Qui est crédité de l'invention de l'ampoule ?", options: ["Nikola Tesla", "Thomas Edison", "Alexander Graham Bell", "James Watt"], correctAnswerIndex: 1 },
    { question: "Quelle planète est la plus proche du Soleil ?", options: ["Vénus", "Mars", "Mercure", "Terre"], correctAnswerIndex: 2 },
    { question: "Dans quel pays se trouve le canal de Suez ?", options: ["Panama", "Égypte", "Turquie", "Grèce"], correctAnswerIndex: 1 },
    { question: "Quel est le minéral le plus dur connu ?", options: ["Quartz", "Topaze", "Corindon", "Diamant"], correctAnswerIndex: 3 },
    { question: "Combien de côtés a un octogone ?", options: ["6", "8", "10", "12"], correctAnswerIndex: 1 },
    { question: "Qui a écrit 'L'Odyssée' ?", options: ["Homère", "Virgile", "Sophocle", "Platon"], correctAnswerIndex: 0 },
    { question: "Quelle est la plus grande île du monde ?", options: ["Groenland", "Nouvelle-Guinée", "Bornéo", "Madagascar"], correctAnswerIndex: 0 },
    { question: "Quelle est la capitale de la Corée du Sud ?", options: ["Pyongyang", "Séoul", "Busan", "Incheon"], correctAnswerIndex: 1 },
    { question: "Quel gaz est le plus abondant dans l'atmosphère terrestre ?", options: ["Oxygène", "Hydrogène", "Azote", "Dioxyde de carbone"], correctAnswerIndex: 2 },
    { question: "Qui a été la première femme à traverser l'Atlantique en solo ?", options: ["Bessie Coleman", "Harriet Quimby", "Amelia Earhart", "Jacqueline Cochran"], correctAnswerIndex: 2 },
    { question: "Comment s'appelle la peur des araignées ?", options: ["Agoraphobie", "Acrophobie", "Claustrophobie", "Arachnophobie"], correctAnswerIndex: 3 },
    { question: "Quelle est la capitale de la Nouvelle-Zélande ?", options: ["Auckland", "Wellington", "Christchurch", "Hamilton"], correctAnswerIndex: 1 },
    { question: "Qui a réalisé le film 'Les Dents de la mer' ?", options: ["George Lucas", "Alfred Hitchcock", "Steven Spielberg", "Martin Scorsese"], correctAnswerIndex: 2 },
    { question: "Quel est l'ingrédient principal d'une soupe miso japonaise traditionnelle ?", options: ["Tofu", "Algues", "Pâte de miso", "Dashi"], correctAnswerIndex: 2 },
    { question: "Combien de cœurs a une pieuvre ?", options: ["1", "2", "3", "4"], correctAnswerIndex: 2 },
    { question: "Quel est le nom du fleuve qui traverse Londres ?", options: ["Seine", "Tamise", "Danube", "Tibre"], correctAnswerIndex: 1 },
    { question: "Qui a écrit 'Orgueil et Préjugés' ?", options: ["Emily Brontë", "Jane Austen", "Mary Shelley", "George Eliot"], correctAnswerIndex: 1 },
    { question: "Quel est le plus grand os du corps humain ?", options: ["Humérus", "Tibia", "Fémur", "Péroné"], correctAnswerIndex: 2 },
    { question: "Quel est le plus petit pays du monde ?", options: ["Monaco", "Nauru", "Tuvalu", "Cité du Vatican"], correctAnswerIndex: 3 },
    { question: "Quel est le seul mammifère capable de voler ?", options: ["Écureuil volant", "Chauve-souris", "Phalanger volant", "Colugo"], correctAnswerIndex: 1 },
    { question: "Quelle est la monnaie de la Suisse ?", options: ["Euro", "Franc suisse", "Dollar", "Livre"], correctAnswerIndex: 1 },
    { question: "Qui a découvert la gravité ?", options: ["Albert Einstein", "Galilée", "Isaac Newton", "Nikola Tesla"], correctAnswerIndex: 2 },
    { question: "Quelle est la capitale de l'Espagne ?", options: ["Barcelone", "Lisbonne", "Madrid", "Séville"], correctAnswerIndex: 2 },
    { question: "Quel élément 'Fe' représente-t-il sur le tableau périodique ?", options: ["Fluor", "Fer", "Or", "Plomb"], correctAnswerIndex: 1 },
    { question: "Quelle est la plus longue chaîne de montagnes continentale du monde ?", options: ["Himalaya", "Rocheuses", "Andes", "Alpes"], correctAnswerIndex: 2 },
    { question: "Qui a peint le plafond de la chapelle Sixtine ?", options: ["Raphaël", "Donatello", "Léonard de Vinci", "Michel-Ange"], correctAnswerIndex: 3 },
    { question: "Quelle est la formule chimique de l'Ozone ?", options: ["O", "O2", "O3", "O4"], correctAnswerIndex: 2 },
    { question: "Quel sport est joué à Wimbledon ?", options: ["Golf", "Tennis", "Cricket", "Rugby"], correctAnswerIndex: 1 },
    { question: "Quelle est la plus grande lune du système solaire ?", options: ["Titan", "Ganymède", "Callisto", "Io"], correctAnswerIndex: 1 },
    { question: "Quelle est la capitale de l'Égypte ?", options: ["Alexandrie", "Gizeh", "Le Caire", "Louxor"], correctAnswerIndex: 2 },
    { question: "Quel est le nom du chien dans 'Les Simpson' ?", options: ["Petit Papa Noël", "Snoopy", "Brian", "Scoubidou"], correctAnswerIndex: 0 }
  ],
  es: [
    { question: "¿Cuál es la capital de Francia?", options: ["Berlín", "Madrid", "París", "Roma"], correctAnswerIndex: 2 },
    { question: "¿Qué planeta se conoce como el Planeta Rojo?", options: ["Tierra", "Marte", "Júpiter", "Venus"], correctAnswerIndex: 1 },
    { question: "¿Cuál es el mamífero más grande del mundo?", options: ["Elefante", "Ballena azul", "Jirafa", "Gran tiburón blanco"], correctAnswerIndex: 1 },
    { question: "¿Quién escribió 'Romeo y Julieta'?", options: ["Charles Dickens", "William Shakespeare", "Jane Austen", "Mark Twain"], correctAnswerIndex: 1 },
    { question: "¿Cuál es el símbolo químico del agua?", options: ["O2", "CO2", "H2O", "NaCl"], correctAnswerIndex: 2 },
    { question: "¿Cuántos continentes hay en la Tierra?", options: ["5", "6", "7", "8"], correctAnswerIndex: 2 },
    { question: "¿Cuál es la sustancia natural más dura de la Tierra?", options: ["Oro", "Hierro", "Diamante", "Platino"], correctAnswerIndex: 2 },
    { question: "¿Qué país es el hogar del canguro?", options: ["Sudáfrica", "India", "Australia", "Brasil"], correctAnswerIndex: 2 },
    { question: "¿Quién pintó la Mona Lisa?", options: ["Vincent van Gogh", "Pablo Picasso", "Leonardo da Vinci", "Claude Monet"], correctAnswerIndex: 2 },
    { question: "¿Cuál es el ingrediente principal del guacamole?", options: ["Tomate", "Aguacate", "Cebolla", "Lima"], correctAnswerIndex: 1 },
    { question: "¿En qué año se hundió el Titanic?", options: ["1905", "1912", "1918", "1923"], correctAnswerIndex: 1 },
    { question: "¿Cuál es la moneda de Japón?", options: ["Yuan", "Won", "Yen", "Baht"], correctAnswerIndex: 2 },
    { question: "¿Qué elemento tiene el número atómico 1?", options: ["Helio", "Oxígeno", "Hidrógeno", "Carbono"], correctAnswerIndex: 2 },
    { question: "¿Quién fue la primera persona en caminar sobre la luna?", options: ["Buzz Aldrin", "Yuri Gagarin", "Michael Collins", "Neil Armstrong"], correctAnswerIndex: 3 },
    { question: "¿Cuál es la montaña más alta del mundo?", options: ["K2", "Monte Everest", "Kangchenjunga", "Lhotse"], correctAnswerIndex: 1 },
    { question: "¿Cuál es el idioma principal que se habla en Brasil?", options: ["Español", "Portugués", "Inglés", "Francés"], correctAnswerIndex: 1 },
    { question: "¿Cuál es el océano más grande de la Tierra?", options: ["Océano Atlántico", "Océano Índico", "Océano Ártico", "Océano Pacífico"], correctAnswerIndex: 3 },
    { question: "¿Cuál es la raíz cuadrada de 64?", options: ["6", "7", "8", "9"], correctAnswerIndex: 2 },
    { question: "¿Quién es el autor de la serie de Harry Potter?", options: ["J.R.R. Tolkien", "George R.R. Martin", "J.K. Rowling", "C.S. Lewis"], correctAnswerIndex: 2 },
    { question: "¿Cuál es el nombre de la galaxia en la que se encuentra nuestro sistema solar?", options: ["Andrómeda", "Triángulo", "Remolino", "Vía Láctea"], correctAnswerIndex: 3 },
    { question: "¿Cuántos jugadores hay en un equipo de fútbol estándar en el campo?", options: ["9", "10", "11", "12"], correctAnswerIndex: 2 },
    { question: "¿Qué gas absorben las plantas de la atmósfera?", options: ["Oxígeno", "Dióxido de carbono", "Nitrógeno", "Hidrógeno"], correctAnswerIndex: 1 },
    { question: "¿Qué artista se cortó su propia oreja?", options: ["Pablo Picasso", "Salvador Dalí", "Vincent van Gogh", "Claude Monet"], correctAnswerIndex: 2 },
    { question: "¿Cuál es la capital de Canadá?", options: ["Toronto", "Vancouver", "Montreal", "Ottawa"], correctAnswerIndex: 3 },
    { question: "¿Cuál es el río más largo del mundo?", options: ["Río Amazonas", "Río Nilo", "Río Yangtsé", "Río Mississippi"], correctAnswerIndex: 1 },
    { question: "¿Qué significa 'CPU'?", options: ["Unidad Central de Procesamiento", "Unidad Personal de Computadora", "Unidad de Procesador Central", "Unidad de Procesamiento de Control"], correctAnswerIndex: 0 },
    { question: "¿En qué año terminó la Segunda Guerra Mundial?", options: ["1942", "1945", "1950", "1939"], correctAnswerIndex: 1 },
    { question: "¿Cuál es el desierto más grande del mundo?", options: ["Desierto del Sahara", "Desierto de Arabia", "Desierto de Gobi", "Desierto Polar Antártico"], correctAnswerIndex: 3 },
    { question: "¿Quién inventó el teléfono?", options: ["Thomas Edison", "Alexander Graham Bell", "Nikola Tesla", "Guglielmo Marconi"], correctAnswerIndex: 1 },
    { question: "¿Cuál es el símbolo químico del oro?", options: ["Ag", "Au", "Pb", "Fe"], correctAnswerIndex: 1 },
    { question: "¿Cuántos huesos hay en el cuerpo humano adulto?", options: ["206", "212", "198", "220"], correctAnswerIndex: 0 },
    { question: "¿Qué país es conocido como la Tierra del Sol Naciente?", options: ["China", "Corea del Sur", "Japón", "Tailandia"], correctAnswerIndex: 2 },
    { question: "¿Cuál es el componente principal de la atmósfera de la Tierra?", options: ["Oxígeno", "Dióxido de carbono", "Nitrógeno", "Argón"], correctAnswerIndex: 2 },
    { question: "¿Quién descubrió la penicilina?", options: ["Marie Curie", "Louis Pasteur", "Alexander Fleming", "Robert Koch"], correctAnswerIndex: 2 },
    { question: "¿Cuál es la capital de Australia?", options: ["Sídney", "Melbourne", "Canberra", "Perth"], correctAnswerIndex: 2 },
    { question: "¿Cuántos planetas hay en nuestro sistema solar?", options: ["7", "8", "9", "10"], correctAnswerIndex: 1 },
    { question: "¿Cuál es el animal terrestre más rápido?", options: ["León", "Berrendo", "Guepardo", "Ñu"], correctAnswerIndex: 2 },
    { question: "¿Cuál es el punto de ebullición del agua en Celsius?", options: ["90°C", "100°C", "110°C", "120°C"], correctAnswerIndex: 1 },
    { question: "¿Quién escribió 'El Gran Gatsby'?", options: ["F. Scott Fitzgerald", "Ernest Hemingway", "William Faulkner", "John Steinbeck"], correctAnswerIndex: 0 },
    { question: "¿Cuál es la moneda del Reino Unido?", options: ["Euro", "Dólar", "Libra esterlina", "Franco"], correctAnswerIndex: 2 },
    { question: "¿Cuál es el continente más pequeño?", options: ["Europa", "América del Sur", "Antártida", "Australia"], correctAnswerIndex: 3 },
    { question: "¿Cuál es el idioma oficial de Egipto?", options: ["Inglés", "Francés", "Árabe", "Egipcio"], correctAnswerIndex: 2 },
    { question: "¿Quién fue el primer presidente de los Estados Unidos?", options: ["Thomas Jefferson", "Abraham Lincoln", "George Washington", "John Adams"], correctAnswerIndex: 2 },
    { question: "¿Cuál es el idioma más hablado en el mundo?", options: ["Español", "Inglés", "Chino mandarín", "Hindi"], correctAnswerIndex: 2 },
    { question: "¿Cuál es el órgano más grande del cuerpo humano?", options: ["Hígado", "Cerebro", "Corazón", "Piel"], correctAnswerIndex: 3 },
    { question: "¿Qué producen las abejas?", options: ["Jarabe", "Miel", "Néctar", "Polen"], correctAnswerIndex: 1 },
    { question: "¿Qué famoso científico desarrolló la teoría de la relatividad?", options: ["Isaac Newton", "Galileo Galilei", "Albert Einstein", "Stephen Hawking"], correctAnswerIndex: 2 },
    { question: "¿Cuántos lados tiene un hexágono?", options: ["5", "6", "7", "8"], correctAnswerIndex: 1 },
    { question: "¿En qué océano se encuentra el Triángulo de las Bermudas?", options: ["Pacífico", "Índico", "Ártico", "Atlántico"], correctAnswerIndex: 3 },
    { question: "¿Cuál es el personaje principal de la serie 'El Señor de los Anillos'?", options: ["Harry Potter", "Frodo Bolsón", "Luke Skywalker", "Jon Nieve"], correctAnswerIndex: 1 },
    { question: "¿Cuál es la capital de Italia?", options: ["Venecia", "Florencia", "Milán", "Roma"], correctAnswerIndex: 3 },
    { question: "¿Cuál es la fórmula química de la sal de mesa?", options: ["H2O", "CO2", "NaCl", "C6H12O6"], correctAnswerIndex: 2 },
    { question: "¿Qué animal es conocido como el 'Rey de la Selva'?", options: ["Tigre", "Elefante", "León", "Gorila"], correctAnswerIndex: 2 },
    { question: "¿Cuál es el término para una palabra que se lee igual hacia adelante y hacia atrás?", options: ["Sinónimo", "Antónimo", "Palíndromo", "Anagrama"], correctAnswerIndex: 2 },
    { question: "¿Cuántos colores hay en un arcoíris?", options: ["5", "6", "7", "8"], correctAnswerIndex: 2 },
    { question: "¿En qué país encontrarías la Gran Muralla?", options: ["India", "Egipto", "China", "Perú"], correctAnswerIndex: 2 },
    { question: "¿Cuál es el nombre del mago en 'El Hobbit'?", options: ["Dumbledore", "Gandalf", "Merlín", "Saruman"], correctAnswerIndex: 1 },
    { question: "¿Qué tipo de pez es Nemo en la película 'Buscando a Nemo'?", options: ["Pez dorado", "Pez payaso", "Pez ángel", "Guppy"], correctAnswerIndex: 1 },
    { question: "¿Cuál es el país más grande del mundo por área?", options: ["Canadá", "China", "EE.UU.", "Rusia"], correctAnswerIndex: 3 },
    { question: "¿Cuál es el nombre del vaquero de juguete en 'Toy Story'?", options: ["Buzz Lightyear", "Woody", "Sr. Cara de Papa", "Slinky Dog"], correctAnswerIndex: 1 },
    { question: "¿Cuál es el gas principal que compone el Sol?", options: ["Oxígeno", "Helio", "Hidrógeno", "Carbono"], correctAnswerIndex: 2 },
    { question: "¿Quién es el dios griego del mar?", options: ["Zeus", "Hades", "Poseidón", "Apolo"], correctAnswerIndex: 2 },
    { question: "¿Qué ciudad es famosa por su torre inclinada?", options: ["Roma", "Pisa", "Florencia", "Venecia"], correctAnswerIndex: 1 },
    { question: "¿Cuál es la capital de Rusia?", options: ["San Petersburgo", "Moscú", "Kazán", "Novosibirsk"], correctAnswerIndex: 1 },
    { question: "¿Cuántas cuerdas tiene un violín?", options: ["4", "5", "6", "7"], correctAnswerIndex: 0 },
    { question: "¿Cuál es el deporte nacional de Canadá?", options: ["Hockey y Lacrosse", "Béisbol", "Fútbol", "Curling"], correctAnswerIndex: 0 },
    { question: "¿Cómo se llama un grupo de leones?", options: ["Una manada", "Una jauría", "Una manada de leones", "Una bandada"], correctAnswerIndex: 2 },
    { question: "¿En qué continente está España?", options: ["Asia", "África", "Europa", "América del Sur"], correctAnswerIndex: 2 },
    { question: "¿Cuál es la moneda de la India?", options: ["Rupia", "Yen", "Dólar", "Euro"], correctAnswerIndex: 0 },
    { question: "¿Cuál es el número primo más pequeño?", options: ["0", "1", "2", "3"], correctAnswerIndex: 2 },
    { question: "¿Quién pintó 'La noche estrellada'?", options: ["Claude Monet", "Vincent van Gogh", "Pablo Picasso", "Salvador Dalí"], correctAnswerIndex: 1 },
    { question: "¿Cuál es la capital de Argentina?", options: ["Santiago", "Lima", "Buenos Aires", "Bogotá"], correctAnswerIndex: 2 },
    { question: "¿Cuál es el símbolo químico de la Plata?", options: ["Si", "Sv", "Ag", "Sl"], correctAnswerIndex: 2 },
    { question: "¿A quién se le atribuye la invención de la bombilla?", options: ["Nikola Tesla", "Thomas Edison", "Alexander Graham Bell", "James Watt"], correctAnswerIndex: 1 },
    { question: "¿Qué planeta está más cerca del Sol?", options: ["Venus", "Marte", "Mercurio", "Tierra"], correctAnswerIndex: 2 },
    { question: "¿En qué país se encuentra el Canal de Suez?", options: ["Panamá", "Egipto", "Turquía", "Grecia"], correctAnswerIndex: 1 },
    { question: "¿Cuál es el mineral más duro conocido?", options: ["Cuarzo", "Topacio", "Corindón", "Diamante"], correctAnswerIndex: 3 },
    { question: "¿Cuántos lados tiene un octágono?", options: ["6", "8", "10", "12"], correctAnswerIndex: 1 },
    { question: "¿Quién escribió 'La Odisea'?", options: ["Homero", "Virgilio", "Sófocles", "Platón"], correctAnswerIndex: 0 },
    { question: "¿Cuál es la isla más grande del mundo?", options: ["Groenlandia", "Nueva Guinea", "Borneo", "Madagascar"], correctAnswerIndex: 0 },
    { question: "¿Cuál es la capital de Corea del Sur?", options: ["Pyongyang", "Seúl", "Busan", "Incheon"], correctAnswerIndex: 1 },
    { question: "¿Qué gas es más abundante en la atmósfera de la Tierra?", options: ["Oxígeno", "Hidrógeno", "Nitrógeno", "Dióxido de carbono"], correctAnswerIndex: 2 },
    { question: "¿Quién fue la primera mujer en volar sola a través del Océano Atlántico?", options: ["Bessie Coleman", "Harriet Quimby", "Amelia Earhart", "Jacqueline Cochran"], correctAnswerIndex: 2 },
    { question: "¿Cómo se llama el miedo a las arañas?", options: ["Agorafobia", "Acrofobia", "Claustrofobia", "Aracnofobia"], correctAnswerIndex: 3 },
    { question: "¿Cuál es la capital de Nueva Zelanda?", options: ["Auckland", "Wellington", "Christchurch", "Hamilton"], correctAnswerIndex: 1 },
    { question: "¿Quién dirigió la película 'Tiburón'?", options: ["George Lucas", "Alfred Hitchcock", "Steven Spielberg", "Martin Scorsese"], correctAnswerIndex: 2 },
    { question: "¿Cuál es el ingrediente principal de una sopa de miso tradicional japonesa?", options: ["Tofu", "Algas", "Pasta de miso", "Dashi"], correctAnswerIndex: 2 },
    { question: "¿Cuántos corazones tiene un pulpo?", options: ["1", "2", "3", "4"], correctAnswerIndex: 2 },
    { question: "¿Cuál es el nombre del río que atraviesa Londres?", options: ["Sena", "Támesis", "Danubio", "Tíber"], correctAnswerIndex: 1 },
    { question: "¿Quién escribió 'Orgullo y prejuicio'?", options: ["Emily Brontë", "Jane Austen", "Mary Shelley", "George Eliot"], correctAnswerIndex: 1 },
    { question: "¿Cuál es el hueso más grande del cuerpo humano?", options: ["Húmero", "Tibia", "Fémur", "Peroné"], correctAnswerIndex: 2 },
    { question: "¿Cuál es el país más pequeño del mundo?", options: ["Mónaco", "Nauru", "Tuvalu", "Ciudad del Vaticano"], correctAnswerIndex: 3 },
    { question: "¿Cuál es el único mamífero capaz de volar de verdad?", options: ["Ardilla voladora", "Murciélago", "Petauro del azúcar", "Colugo"], correctAnswerIndex: 1 },
    { question: "¿Cuál es la moneda de Suiza?", options: ["Euro", "Franco suizo", "Dólar", "Libra"], correctAnswerIndex: 1 },
    { question: "¿Quién descubrió la gravedad?", options: ["Albert Einstein", "Galileo Galilei", "Isaac Newton", "Nikola Tesla"], correctAnswerIndex: 2 },
    { question: "¿Cuál es la capital de España?", options: ["Barcelona", "Lisboa", "Madrid", "Sevilla"], correctAnswerIndex: 2 },
    { question: "¿Qué elemento representa 'Fe' en la tabla periódica?", options: ["Flúor", "Hierro", "Oro", "Plomo"], correctAnswerIndex: 1 },
    { question: "¿Cuál es la cordillera continental más larga del mundo?", options: ["Himalaya", "Montañas Rocosas", "Andes", "Alpes"], correctAnswerIndex: 2 },
    { question: "¿Quién pintó el techo de la Capilla Sixtina?", options: ["Rafael", "Donatello", "Leonardo da Vinci", "Miguel Ángel"], correctAnswerIndex: 3 },
    { question: "¿Cuál es la fórmula química del Ozono?", options: ["O", "O2", "O3", "O4"], correctAnswerIndex: 2 },
    { question: "¿Qué deporte se juega en Wimbledon?", options: ["Golf", "Tenis", "Críquet", "Rugby"], correctAnswerIndex: 1 },
    { question: "¿Cuál es la luna más grande del Sistema Solar?", options: ["Titán", "Ganimedes", "Calisto", "Ío"], correctAnswerIndex: 1 },
    { question: "¿Cuál es la capital de Egipto?", options: ["Alejandría", "Giza", "El Cairo", "Luxor"], correctAnswerIndex: 2 },
    { question: "¿Cuál es el nombre del perro en 'Los Simpson'?", options: ["Pequeño Ayudante de Santa", "Snoopy", "Brian", "Scooby-Doo"], correctAnswerIndex: 0 }
  ],
  mg: [
    { question: "Inona ny renivohitr'i Frantsa?", options: ["Berlin", "Madrid", "Paris", "Roma"], correctAnswerIndex: 2 },
    { question: "Iza no planeta fantatra amin'ny anarana hoe Planeta Mena?", options: ["Tany", "Mars", "Jupiter", "Venus"], correctAnswerIndex: 1 },
    { question: "Inona no biby mampinono lehibe indrindra eran-tany?", options: ["Elefanta", "Baleine Bleue", "Zirafy", "Requin Blanc Lehibe"], correctAnswerIndex: 1 },
    { question: "Iza no nanoratra ny 'Romeo sy Juliet'?", options: ["Charles Dickens", "William Shakespeare", "Jane Austen", "Mark Twain"], correctAnswerIndex: 1 },
    { question: "Inona no eva simikan'ny rano?", options: ["O2", "CO2", "H2O", "NaCl"], correctAnswerIndex: 2 },
    { question: "Firy ny kaontinanta eto an-tany?", options: ["5", "6", "7", "8"], correctAnswerIndex: 2 },
    { question: "Inona no zavatra voajanahary mafy indrindra eto an-tany?", options: ["Volamena", "Vy", "Diamondra", "Platina"], correctAnswerIndex: 2 },
    { question: "Firenena iza no misy ny kangoroa?", options: ["Afrika Atsimo", "India", "Aostralia", "Brezila"], correctAnswerIndex: 2 },
    { question: "Iza no nandoko ny Mona Lisa?", options: ["Vincent van Gogh", "Pablo Picasso", "Leonardo da Vinci", "Claude Monet"], correctAnswerIndex: 2 },
    { question: "Inona no akora fototra amin'ny guacamole?", options: ["Voatabia", "Zavoka", "Tongolo", "Voasary makirana"], correctAnswerIndex: 1 },
    { question: "Tamin'ny taona firy no nilentika ny Titanic?", options: ["1905", "1912", "1918", "1923"], correctAnswerIndex: 1 },
    { question: "Inona no volan'i Japana?", options: ["Yuan", "Won", "Yen", "Baht"], correctAnswerIndex: 2 },
    { question: "Singa iza no manana ny laharana atomika 1?", options: ["Hélium", "Oksizenina", "Hidrozenina", "Karbonina"], correctAnswerIndex: 2 },
    { question: "Iza no olona voalohany nandeha teny amin'ny volana?", options: ["Buzz Aldrin", "Yuri Gagarin", "Michael Collins", "Neil Armstrong"], correctAnswerIndex: 3 },
    { question: "Inona no tendrombohitra avo indrindra eran-tany?", options: ["K2", "Tendrombohitra Everest", "Kangchenjunga", "Lhotse"], correctAnswerIndex: 1 },
    { question: "Inona no fiteny fototra ampiasaina any Brezila?", options: ["Espaniola", "Portiogey", "Anglisy", "Frantsay"], correctAnswerIndex: 1 },
    { question: "Iza no ranomasina lehibe indrindra eto an-tany?", options: ["Ranomasina Atlantika", "Ranomasina Indianina", "Ranomasina Arktika", "Ranomasina Pasifika"], correctAnswerIndex: 3 },
    { question: "Firy ny fakan-toradroan'ny 64?", options: ["6", "7", "8", "9"], correctAnswerIndex: 2 },
    { question: "Iza no mpanoratra ny andian-dahatsoratra Harry Potter?", options: ["J.R.R. Tolkien", "George R.R. Martin", "J.K. Rowling", "C.S. Lewis"], correctAnswerIndex: 2 },
    { question: "Inona no anaran'ny vahindanitra misy ny rafi-masoandrontsika?", options: ["Andromeda", "Triangulum", "Whirlpool", "Milky Way"], correctAnswerIndex: 3 },
    { question: "Firy ny mpilalao ao anaty ekipa baolina kitra mahazatra eny an-kianja?", options: ["9", "10", "11", "12"], correctAnswerIndex: 2 },
    { question: "Inona no etona raisin'ny zavamaniry avy amin'ny atmosfera?", options: ["Oksizenina", "Dioksidan'ny Karbonina", "Nitrogenina", "Hidrozenina"], correctAnswerIndex: 1 },
    { question: "Mpanakanto iza no nanapaka ny sofiny?", options: ["Pablo Picasso", "Salvador Dalí", "Vincent van Gogh", "Claude Monet"], correctAnswerIndex: 2 },
    { question: "Inona ny renivohitr'i Kanada?", options: ["Toronto", "Vancouver", "Montreal", "Ottawa"], correctAnswerIndex: 3 },
    { question: "Iza no renirano lava indrindra eran-tany?", options: ["Reniranon'i Amazona", "Reniranon'i Neily", "Reniranon'i Yangtze", "Reniranon'i Mississippi"], correctAnswerIndex: 1 },
    { question: "Inona no dikan'ny 'CPU'?", options: ["Central Processing Unit", "Computer Personal Unit", "Central Processor Unit", "Control Processing Unit"], correctAnswerIndex: 0 },
    { question: "Tamin'ny taona firy no nifarana ny Ady Lehibe Faharoa?", options: ["1942", "1945", "1950", "1939"], correctAnswerIndex: 1 },
    { question: "Inona no tany efitra lehibe indrindra eran-tany?", options: ["Tany efitr'i Sahara", "Tany efitr'i Arabia", "Tany efitr'i Gobi", "Tany efitra polar antarktika"], correctAnswerIndex: 3 },
    { question: "Iza no namorona ny telefaonina?", options: ["Thomas Edison", "Alexander Graham Bell", "Nikola Tesla", "Guglielmo Marconi"], correctAnswerIndex: 1 },
    { question: "Inona no eva simikan'ny volamena?", options: ["Ag", "Au", "Pb", "Fe"], correctAnswerIndex: 1 },
    { question: "Firy ny taolana ao amin'ny vatan'olombelona lehibe?", options: ["206", "212", "198", "220"], correctAnswerIndex: 0 },
    { question: "Firenena iza no fantatra amin'ny anarana hoe Tanyn'ny Masoandro Miposaka?", options: ["Sina", "Korea Atsimo", "Japana", "Thailand"], correctAnswerIndex: 2 },
    { question: "Inona no singa fototra amin'ny atmosfera eto an-tany?", options: ["Oksizenina", "Dioksidan'ny Karbonina", "Nitrogenina", "Argon"], correctAnswerIndex: 2 },
    { question: "Iza no nahita ny penisilinina?", options: ["Marie Curie", "Louis Pasteur", "Alexander Fleming", "Robert Koch"], correctAnswerIndex: 2 },
    { question: "Inona ny renivohitr'i Aostralia?", options: ["Sydney", "Melbourne", "Canberra", "Perth"], correctAnswerIndex: 2 },
    { question: "Firy ny planeta ao amin'ny rafi-masoandrontsika?", options: ["7", "8", "9", "10"], correctAnswerIndex: 1 },
    { question: "Inona no biby an-tanety haingam-pandeha indrindra?", options: ["Liona", "Pronghorn", "Guepard", "Wildebeest"], correctAnswerIndex: 2 },
    { question: "Inona no mari-pana andrahoan'ny rano amin'ny Celsius?", options: ["90°C", "100°C", "110°C", "120°C"], correctAnswerIndex: 1 },
    { question: "Iza no nanoratra ny 'The Great Gatsby'?", options: ["F. Scott Fitzgerald", "Ernest Hemingway", "William Faulkner", "John Steinbeck"], correctAnswerIndex: 0 },
    { question: "Inona no volan'ny Fanjakana Mitambatra?", options: ["Euro", "Dollar", "Pound Sterling", "Franc"], correctAnswerIndex: 2 },
    { question: "Iza no kaontinanta kely indrindra?", options: ["Eoropa", "Amerika Atsimo", "Antarktika", "Aostralia"], correctAnswerIndex: 3 },
    { question: "Inona no fiteny ofisialin'i Ejipta?", options: ["Anglisy", "Frantsay", "Arabo", "Ejipsianina"], correctAnswerIndex: 2 },
    { question: "Iza no Filoha voalohany an'i Etazonia?", options: ["Thomas Jefferson", "Abraham Lincoln", "George Washington", "John Adams"], correctAnswerIndex: 2 },
    { question: "Inona no fiteny be mpampiasa indrindra eran-tany?", options: ["Espaniola", "Anglisy", "Sinoa Mandarin", "Hindi"], correctAnswerIndex: 2 },
    { question: "Inona no taova lehibe indrindra amin'ny vatan'olombelona?", options: ["Aty", "Atidoha", "Fo", "Hodi-koditra"], correctAnswerIndex: 3 },
    { question: "Inona no vokarin'ny tantely?", options: ["Sirop", "Tantely", "Nectar", "Pollen"], correctAnswerIndex: 1 },
    { question: "Iza ilay mpahay siansa malaza namorona ny teôrian'ny relativité?", options: ["Isaac Newton", "Galileo Galilei", "Albert Einstein", "Stephen Hawking"], correctAnswerIndex: 2 },
    { question: "Firy ny sisin'ny hexagon?", options: ["5", "6", "7", "8"], correctAnswerIndex: 1 },
    { question: "Ao amin'ny ranomasina iza no misy ny Telozoron'i Bermuda?", options: ["Pasifika", "Indianina", "Arktika", "Atlantika"], correctAnswerIndex: 3 },
    { question: "Iza no mpilalao fototra ao amin'ny andian-tantara 'Lord of the Rings'?", options: ["Harry Potter", "Frodo Baggins", "Luke Skywalker", "Jon Snow"], correctAnswerIndex: 1 },
    { question: "Inona ny renivohitr'i Italia?", options: ["Venise", "Florence", "Milan", "Roma"], correctAnswerIndex: 3 },
    { question: "Inona no raikipohy simika ho an'ny sira fihinana?", options: ["H2O", "CO2", "NaCl", "C6H12O6"], correctAnswerIndex: 2 },
    { question: "Biby iza no fantatra amin'ny anarana hoe 'Mpanjakan'ny Ala'?", options: ["Tigra", "Elefanta", "Liona", "Gorila"], correctAnswerIndex: 2 },
    { question: "Inona no teny ilazana ny teny iray izay mitovy vakiana avy eo aloha sy avy ao aoriana?", options: ["Synonyme", "Antonyme", "Palindrome", "Anagramme"], correctAnswerIndex: 2 },
    { question: "Firy ny lokon'ny avana?", options: ["5", "6", "7", "8"], correctAnswerIndex: 2 },
    { question: "Any amin'ny firenena iza no ahitanao ny Rindrim-be?", options: ["India", "Ejipta", "Sina", "Peroa"], correctAnswerIndex: 2 },
    { question: "Iza no anaran'ilay mpamosavy ao amin'ny 'The Hobbit'?", options: ["Dumbledore", "Gandalf", "Merlin", "Saruman"], correctAnswerIndex: 1 },
    { question: "Karazana trondro inona i Nemo ao amin'ny sarimihetsika 'Finding Nemo'?", options: ["Trondro volamena", "Trondro clown", "Trondro anjely", "Guppy"], correctAnswerIndex: 1 },
    { question: "Inona no firenena lehibe indrindra eran-tany raha ny velarany no jerena?", options: ["Kanada", "Sina", "Etazonia", "Rosia"], correctAnswerIndex: 3 },
    { question: "Iza no anaran'ilay kilalao cowboy ao amin'ny 'Toy Story'?", options: ["Buzz Lightyear", "Woody", "Mr. Potato Head", "Slinky Dog"], correctAnswerIndex: 1 },
    { question: "Inona no entona fototra mandrafitra ny Masoandro?", options: ["Oksizenina", "Hélium", "Hidrozenina", "Karbonina"], correctAnswerIndex: 2 },
    { question: "Iza no andriamanitra grika an'ny ranomasina?", options: ["Zeus", "Hades", "Poseidon", "Apollo"], correctAnswerIndex: 2 },
    { question: "Tanàna iza no malaza amin'ny tilikambo mitongilana?", options: ["Roma", "Pise", "Florence", "Venise"], correctAnswerIndex: 1 },
    { question: "Inona ny renivohitr'i Rosia?", options: ["Saint Petersburg", "Moskoa", "Kazan", "Novosibirsk"], correctAnswerIndex: 1 },
    { question: "Firy ny tadin'ny lokanga?", options: ["4", "5", "6", "7"], correctAnswerIndex: 0 },
    { question: "Inona no fanatanjahantena nasionalin'i Kanada?", options: ["Hockey sy Lacrosse", "Baseball", "Baolina kitra", "Curling"], correctAnswerIndex: 0 },
    { question: "Inona no iantsoana ny andian-diona?", options: ["Andiany", "Andiany", "Fianakaviana", "Andiany"], correctAnswerIndex: 2 },
    { question: "Kaontinanta iza no misy an'i Espaina?", options: ["Azia", "Afrika", "Eoropa", "Amerika Atsimo"], correctAnswerIndex: 2 },
    { question: "Inona no volan'i India?", options: ["Roupie", "Yen", "Dollar", "Euro"], correctAnswerIndex: 0 },
    { question: "Inona no isa praiminisitra kely indrindra?", options: ["0", "1", "2", "3"], correctAnswerIndex: 2 },
    { question: "Iza no nandoko ny 'Alina feno kintana'?", options: ["Claude Monet", "Vincent van Gogh", "Pablo Picasso", "Salvador Dalí"], correctAnswerIndex: 1 },
    { question: "Inona no renivohitr'i Arzantina?", options: ["Santiago", "Lima", "Buenos Aires", "Bogotá"], correctAnswerIndex: 2 },
    { question: "Inona no eva simikan'ny Volafotsy?", options: ["Si", "Sv", "Ag", "Sl"], correctAnswerIndex: 2 },
    { question: "Iza no omena voninahitra tamin'ny famoronana ny jiro?", options: ["Nikola Tesla", "Thomas Edison", "Alexander Graham Bell", "James Watt"], correctAnswerIndex: 1 },
    { question: "Planeta iza no akaiky indrindra ny Masoandro?", options: ["Venus", "Mars", "Mercure", "Tany"], correctAnswerIndex: 2 },
    { question: "Any amin'ny firenena iza no misy ny Lakandranon'i Suez?", options: ["Panama", "Ejipta", "Torkia", "Gresy"], correctAnswerIndex: 1 },
    { question: "Inona no mineraly mafy indrindra fantatra?", options: ["Quartz", "Topaze", "Corindon", "Diamondra"], correctAnswerIndex: 3 },
    { question: "Firy ny sisin'ny octagon?", options: ["6", "8", "10", "12"], correctAnswerIndex: 1 },
    { question: "Iza no nanoratra ny 'L'Odyssée'?", options: ["Homer", "Virgil", "Sophocle", "Platon"], correctAnswerIndex: 0 },
    { question: "Inona no nosy lehibe indrindra eran-tany?", options: ["Groenland", "Ginea Vaovao", "Borneo", "Madagasikara"], correctAnswerIndex: 0 },
    { question: "Inona no renivohitr'i Korea Atsimo?", options: ["Pyongyang", "Seoul", "Busan", "Incheon"], correctAnswerIndex: 1 },
    { question: "Inona no entona be indrindra amin'ny atmosfera eto an-tany?", options: ["Oksizenina", "Hidrozenina", "Nitrogenina", "Dioksidan'ny Karbonina"], correctAnswerIndex: 2 },
    { question: "Iza no vehivavy voalohany nanidina irery namakivaky ny Oseana Atlantika?", options: ["Bessie Coleman", "Harriet Quimby", "Amelia Earhart", "Jacqueline Cochran"], correctAnswerIndex: 2 },
    { question: "Ahoana no iantsoana ny tahotra hala?", options: ["Agoraphobie", "Acrophobie", "Claustrophobie", "Arachnophobie"], correctAnswerIndex: 3 },
    { question: "Inona no renivohitr'i Nouvelle-Zélande?", options: ["Auckland", "Wellington", "Christchurch", "Hamilton"], correctAnswerIndex: 1 },
    { question: "Iza no tale tamin'ny sarimihetsika 'Jaws'?", options: ["George Lucas", "Alfred Hitchcock", "Steven Spielberg", "Martin Scorsese"], correctAnswerIndex: 2 },
    { question: "Inona no akora fototra amin'ny lasopy miso japoney nentim-paharazana?", options: ["Tofu", "Ahidrano", "Pâte miso", "Dashi"], correctAnswerIndex: 2 },
    { question: "Firy ny fon'ny horita?", options: ["1", "2", "3", "4"], correctAnswerIndex: 2 },
    { question: "Inona no anaran'ny renirano mamakivaky an'i Londres?", options: ["Seine", "Thames", "Danube", "Tiber"], correctAnswerIndex: 1 },
    { question: "Iza no nanoratra ny 'Orgueil et Préjugés'?", options: ["Emily Brontë", "Jane Austen", "Mary Shelley", "George Eliot"], correctAnswerIndex: 1 },
    { question: "Inona no taolana lehibe indrindra amin'ny vatan'olombelona?", options: ["Humerus", "Tibia", "Femur", "Fibula"], correctAnswerIndex: 2 },
    { question: "Inona no firenena kely indrindra eran-tany?", options: ["Monaco", "Nauru", "Tuvalu", "Vatican City"], correctAnswerIndex: 3 },
    { question: "Iza no hany biby mampinono afaka manidina marina?", options: ["Ecureuil volant", "Ramanavy", "Phalanger volant", "Colugo"], correctAnswerIndex: 1 },
    { question: "Inona no volan'i Soisa?", options: ["Euro", "Franc suisse", "Dollar", "Livre"], correctAnswerIndex: 1 },
    { question: "Iza no nahita ny sinton'ny tany?", options: ["Albert Einstein", "Galileo Galilei", "Isaac Newton", "Nikola Tesla"], correctAnswerIndex: 2 },
    { question: "Inona no renivohitr'i Espaina?", options: ["Barcelone", "Lisbonne", "Madrid", "Séville"], correctAnswerIndex: 2 },
    { question: "Singa inona no asehon'ny 'Fe' eo amin'ny tabilao periodika?", options: ["Fluor", "Vy", "Volamena", "Firaka"], correctAnswerIndex: 1 },
    { question: "Inona no tandavan-tendrombohitra kaontinantaly lava indrindra eran-tany?", options: ["Himalaya", "Rocheuses", "Andes", "Alpes"], correctAnswerIndex: 2 },
    { question: "Iza no nandoko ny valindrihan'ny Chapelle Sixtine?", options: ["Raphaël", "Donatello", "Leonardo da Vinci", "Michel-Ange"], correctAnswerIndex: 3 },
    { question: "Inona no raikipohy simikan'ny Ozone?", options: ["O", "O2", "O3", "O4"], correctAnswerIndex: 2 },
    { question: "Fanatanjahantena inona no lalaovina ao Wimbledon?", options: ["Golf", "Tennis", "Cricket", "Rugby"], correctAnswerIndex: 1 },
    { question: "Inona no volana lehibe indrindra ao amin'ny Système Solaire?", options: ["Titan", "Ganymède", "Callisto", "Io"], correctAnswerIndex: 1 },
    { question: "Inona no renivohitr'i Ejipta?", options: ["Alexandrie", "Gizeh", "Le Caire", "Louxor"], correctAnswerIndex: 2 },
    { question: "Iza no anaran'ny alika ao amin'ny 'The Simpsons'?", options: ["Santa's Little Helper", "Snoopy", "Brian", "Scooby-Doo"], correctAnswerIndex: 0 }
  ]
};
