
export type QuizQuestion = {
  question: string;
  options: string[];
  correctAnswerIndex: number;
};

export type LocalizedQuizData = {
    [key in 'en' | 'fr' | 'es' | 'mg']: QuizQuestion[];
}

export const staticQuizData: LocalizedQuizData = {
  en: [
    { question: "What is the capital of France?", options: ["Berlin", "Madrid", "Paris", "Rome"], correctAnswerIndex: 2 },
    { question: "Which planet is known as the Red Planet?", options: ["Earth", "Mars", "Jupiter", "Venus"], correctAnswerIndex: 1 },
    { question: "What is the largest mammal in the world?", options: ["Elephant", "Blue Whale", "Giraffe", "Great White Shark"], correctAnswerIndex: 1 },
    { question: "Who wrote 'Romeo and Juliet'?", options: ["Charles Dickens", "William Shakespeare", "Jane Austen", "Mark Twain"], correctAnswerIndex: 1 },
    { question: "What is the chemical symbol for water?", options: ["O2", "CO2", "H2O", "NaCl"], correctAnswerIndex: 2 },
    { question: "How many continents are there on Earth?", options: ["5", "6", "7", "8"], correctAnswerIndex: 2 },
    { question: "What is the hardest natural substance on Earth?", options: ["Gold", "Iron", "Diamond", "Platinum"], correctAnswerIndex: 2 },
    { question: "Which country is home to the kangaroo?", options: ["South Africa", "India", "Australia", "Brazil"], correctAnswerIndex: 2 },
    { question: "Who painted the Mona Lisa?", options: ["Vincent van Gogh", "Pablo Picasso", "Leonardo da Vinci", "Claude Monet"], correctAnswerIndex: 2 },
    { question: "What is the main ingredient in guacamole?", options: ["Tomato", "Avocado", "Onion", "Lime"], correctAnswerIndex: 1 },
    { question: "In which year did the Titanic sink?", options: ["1905", "1912", "1918", "1923"], correctAnswerIndex: 1 },
    { question: "What is the currency of Japan?", options: ["Yuan", "Won", "Yen", "Baht"], correctAnswerIndex: 2 },
    { question: "Which element has the atomic number 1?", options: ["Helium", "Oxygen", "Hydrogen", "Carbon"], correctAnswerIndex: 2 },
    { question: "Who was the first person to walk on the moon?", options: ["Buzz Aldrin", "Yuri Gagarin", "Michael Collins", "Neil Armstrong"], correctAnswerIndex: 3 },
    { question: "What is the tallest mountain in the world?", options: ["K2", "Mount Everest", "Kangchenjunga", "Lhotse"], correctAnswerIndex: 1 },
    { question: "What is the primary language spoken in Brazil?", options: ["Spanish", "Portuguese", "English", "French"], correctAnswerIndex: 1 },
    { question: "Which is the largest ocean on Earth?", options: ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "Pacific Ocean"], correctAnswerIndex: 3 },
    { question: "What is the square root of 64?", options: ["6", "7", "8", "9"], correctAnswerIndex: 2 },
    { question: "Who is the author of the Harry Potter series?", options: ["J.R.R. Tolkien", "George R.R. Martin", "J.K. Rowling", "C.S. Lewis"], correctAnswerIndex: 2 },
    { question: "What is the name of the galaxy our solar system is in?", options: ["Andromeda", "Triangulum", "Whirlpool", "Milky Way"], correctAnswerIndex: 3 },
    { question: "How many players are on a standard soccer team on the field?", options: ["9", "10", "11", "12"], correctAnswerIndex: 2 },
    { question: "What gas do plants absorb from the atmosphere?", options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"], correctAnswerIndex: 1 },
    { question: "Which artist cut off his own ear?", options: ["Pablo Picasso", "Salvador Dalí", "Vincent van Gogh", "Claude Monet"], correctAnswerIndex: 2 },
    { question: "What is the capital of Canada?", options: ["Toronto", "Vancouver", "Montreal", "Ottawa"], correctAnswerIndex: 3 },
    { question: "Which is the longest river in the world?", options: ["Amazon River", "Nile River", "Yangtze River", "Mississippi River"], correctAnswerIndex: 1 }
  ],
  fr: [
    { question: "Quelle est la capitale de la France ?", options: ["Berlin", "Madrid", "Paris", "Rome"], correctAnswerIndex: 2 },
    { question: "Quelle planète est connue comme la Planète Rouge ?", options: ["Terre", "Mars", "Jupiter", "Vénus"], correctAnswerIndex: 1 },
    { question: "Quel est le plus grand mammifère du monde ?", options: ["Éléphant", "Baleine bleue", "Girafe", "Grand requin blanc"], correctAnswerIndex: 1 },
    { question: "Qui a écrit 'Roméo et Juliette' ?", options: ["Charles Dickens", "William Shakespeare", "Jane Austen", "Mark Twain"], correctAnswerIndex: 1 },
    { question: "Quel est le symbole chimique de l'eau ?", options: ["O2", "CO2", "H2O", "NaCl"], correctAnswerIndex: 2 },
    { question: "Combien de continents y a-t-il sur Terre ?", options: ["5", "6", "7", "8"], correctAnswerIndex: 2 },
    { question: "Quelle est la substance naturelle la plus dure sur Terre ?", options: ["Or", "Fer", "Diamant", "Platine"], correctAnswerIndex: 2 },
    { question: "Quel pays abrite le kangourou ?", options: ["Afrique du Sud", "Inde", "Australie", "Brésil"], correctAnswerIndex: 2 },
    { question: "Qui a peint la Joconde ?", options: ["Vincent van Gogh", "Pablo Picasso", "Léonard de Vinci", "Claude Monet"], correctAnswerIndex: 2 },
    { question: "Quel est l'ingrédient principal du guacamole ?", options: ["Tomate", "Avocat", "Oignon", "Citron vert"], correctAnswerIndex: 1 },
    { question: "En quelle année le Titanic a-t-il coulé ?", options: ["1905", "1912", "1918", "1923"], correctAnswerIndex: 1 },
    { question: "Quelle est la monnaie du Japon ?", options: ["Yuan", "Won", "Yen", "Baht"], correctAnswerIndex: 2 },
    { question: "Quel élément a le numéro atomique 1 ?", options: ["Hélium", "Oxygène", "Hydrogène", "Carbone"], correctAnswerIndex: 2 },
    { question: "Qui a été la première personne à marcher sur la lune ?", options: ["Buzz Aldrin", "Youri Gagarine", "Michael Collins", "Neil Armstrong"], correctAnswerIndex: 3 },
    { question: "Quelle est la plus haute montagne du monde ?", options: ["K2", "Mont Everest", "Kangchenjunga", "Lhotse"], correctAnswerIndex: 1 },
    { question: "Quelle est la langue principale parlée au Brésil ?", options: ["Espagnol", "Portugais", "Anglais", "Français"], correctAnswerIndex: 1 },
    { question: "Quel est le plus grand océan de la Terre ?", options: ["Océan Atlantique", "Océan Indien", "Océan Arctique", "Océan Pacifique"], correctAnswerIndex: 3 },
    { question: "Quelle est la racine carrée de 64 ?", options: ["6", "7", "8", "9"], correctAnswerIndex: 2 },
    { question: "Qui est l'auteur de la série Harry Potter ?", options: ["J.R.R. Tolkien", "George R.R. Martin", "J.K. Rowling", "C.S. Lewis"], correctAnswerIndex: 2 },
    { question: "Quel est le nom de la galaxie de notre système solaire ?", options: ["Andromède", "Triangle", "Tourbillon", "Voie lactée"], correctAnswerIndex: 3 },
    { question: "Combien de joueurs y a-t-il dans une équipe de football standard sur le terrain ?", options: ["9", "10", "11", "12"], correctAnswerIndex: 2 },
    { question: "Quel gaz les plantes absorbent-elles de l'atmosphère ?", options: ["Oxygène", "Dioxyde de carbone", "Azote", "Hydrogène"], correctAnswerIndex: 1 },
    { question: "Quel artiste s'est coupé l'oreille ?", options: ["Pablo Picasso", "Salvador Dalí", "Vincent van Gogh", "Claude Monet"], correctAnswerIndex: 2 },
    { question: "Quelle est la capitale du Canada ?", options: ["Toronto", "Vancouver", "Montréal", "Ottawa"], correctAnswerIndex: 3 },
    { question: "Quel est le plus long fleuve du monde ?", options: ["Amazone", "Nil", "Yangtsé", "Mississippi"], correctAnswerIndex: 1 }
  ],
  es: [
    { question: "¿Cuál es la capital de Francia?", options: ["Berlín", "Madrid", "París", "Roma"], correctAnswerIndex: 2 },
    { question: "¿Qué planeta se conoce como el Planeta Rojo?", options: ["Tierra", "Marte", "Júpiter", "Venus"], correctAnswerIndex: 1 },
    { question: "¿Cuál es el mamífero más grande del mundo?", options: ["Elefante", "Ballena azul", "Jirafa", "Gran tiburón blanco"], correctAnswerIndex: 1 },
    { question: "¿Quién escribió 'Romeo y Julieta'?", options: ["Charles Dickens", "William Shakespeare", "Jane Austen", "Mark Twain"], correctAnswerIndex: 1 },
    { question: "¿Cuál es el símbolo químico del agua?", options: ["O2", "CO2", "H2O", "NaCl"], correctAnswerIndex: 2 },
    { question: "¿Cuántos continentes hay en la Tierra?", options: ["5", "6", "7", "8"], correctAnswerIndex: 2 },
    { question: "¿Cuál es la sustancia natural más dura de la Tierra?", options: ["Oro", "Hierro", "Diamante", "Platino"], correctAnswerIndex: 2 },
    { question: "¿Qué país es el hogar del canguro?", options: ["Sudáfrica", "India", "Australia", "Brasil"], correctAnswerIndex: 2 },
    { question: "¿Quién pintó la Mona Lisa?", options: ["Vincent van Gogh", "Pablo Picasso", "Leonardo da Vinci", "Claude Monet"], correctAnswerIndex: 2 },
    { question: "¿Cuál es el ingrediente principal del guacamole?", options: ["Tomate", "Aguacate", "Cebolla", "Lima"], correctAnswerIndex: 1 },
    { question: "¿En qué año se hundió el Titanic?", options: ["1905", "1912", "1918", "1923"], correctAnswerIndex: 1 },
    { question: "¿Cuál es la moneda de Japón?", options: ["Yuan", "Won", "Yen", "Baht"], correctAnswerIndex: 2 },
    { question: "¿Qué elemento tiene el número atómico 1?", options: ["Helio", "Oxígeno", "Hidrógeno", "Carbono"], correctAnswerIndex: 2 },
    { question: "¿Quién fue la primera persona en caminar sobre la luna?", options: ["Buzz Aldrin", "Yuri Gagarin", "Michael Collins", "Neil Armstrong"], correctAnswerIndex: 3 },
    { question: "¿Cuál es la montaña más alta del mundo?", options: ["K2", "Monte Everest", "Kangchenjunga", "Lhotse"], correctAnswerIndex: 1 },
    { question: "¿Cuál es el idioma principal que se habla en Brasil?", options: ["Español", "Portugués", "Inglés", "Francés"], correctAnswerIndex: 1 },
    { question: "¿Cuál es el océano más grande de la Tierra?", options: ["Océano Atlántico", "Océano Índico", "Océano Ártico", "Océano Pacífico"], correctAnswerIndex: 3 },
    { question: "¿Cuál es la raíz cuadrada de 64?", options: ["6", "7", "8", "9"], correctAnswerIndex: 2 },
    { question: "¿Quién es el autor de la serie de Harry Potter?", options: ["J.R.R. Tolkien", "George R.R. Martin", "J.K. Rowling", "C.S. Lewis"], correctAnswerIndex: 2 },
    { question: "¿Cuál es el nombre de la galaxia en la que se encuentra nuestro sistema solar?", options: ["Andrómeda", "Triángulo", "Remolino", "Vía Láctea"], correctAnswerIndex: 3 },
    { question: "¿Cuántos jugadores hay en un equipo de fútbol estándar en el campo?", options: ["9", "10", "11", "12"], correctAnswerIndex: 2 },
    { question: "¿Qué gas absorben las plantas de la atmósfera?", options: ["Oxígeno", "Dióxido de carbono", "Nitrógeno", "Hidrógeno"], correctAnswerIndex: 1 },
    { question: "¿Qué artista se cortó su propia oreja?", options: ["Pablo Picasso", "Salvador Dalí", "Vincent van Gogh", "Claude Monet"], correctAnswerIndex: 2 },
    { question: "¿Cuál es la capital de Canadá?", options: ["Toronto", "Vancouver", "Montreal", "Ottawa"], correctAnswerIndex: 3 },
    { question: "¿Cuál es el río más largo del mundo?", options: ["Río Amazonas", "Río Nilo", "Río Yangtsé", "Río Mississippi"], correctAnswerIndex: 1 }
  ],
  mg: [
    { question: "Inona ny renivohitr'i Frantsa?", options: ["Berlin", "Madrid", "Paris", "Roma"], correctAnswerIndex: 2 },
    { question: "Iza no planeta fantatra amin'ny anarana hoe Planeta Mena?", options: ["Tany", "Mars", "Jupiter", "Venus"], correctAnswerIndex: 1 },
    { question: "Inona no biby mampinono lehibe indrindra eran-tany?", options: ["Elefanta", "Baleine Bleue", "Zirafy", "Requin Blanc Lehibe"], correctAnswerIndex: 1 },
    { question: "Iza no nanoratra ny 'Romeo sy Juliet'?", options: ["Charles Dickens", "William Shakespeare", "Jane Austen", "Mark Twain"], correctAnswerIndex: 1 },
    { question: "Inona no eva simikan'ny rano?", options: ["O2", "CO2", "H2O", "NaCl"], correctAnswerIndex: 2 },
    { question- "Firy ny kaontinanta eto an-tany?", options: ["5", "6", "7", "8"], correctAnswerIndex: 2 },
    { question: "Inona no zavatra voajanahary mafy indrindra eto an-tany?", options: ["Volamena", "Vy", "Diamondra", "Platina"], correctAnswerIndex: 2 },
    { question: "Firenena iza no misy ny kangoroa?", options: ["Afrika Atsimo", "India", "Aostralia", "Brezila"], correctAnswerIndex: 2 },
    { question: "Iza no nandoko ny Mona Lisa?", options: ["Vincent van Gogh", "Pablo Picasso", "Leonardo da Vinci", "Claude Monet"], correctAnswerIndex: 2 },
    { question: "Inona no akora fototra amin'ny guacamole?", options: ["Voatabia", "Zavoka", "Tongolo", "Voasary makirana"], correctAnswerIndex: 1 },
    { question: "Tamin'ny taona firy no nilentika ny Titanic?", options: ["1905", "1912", "1918", "1923"], correctAnswerIndex: 1 },
    { question: "Inona no volan'i Japana?", options: ["Yuan", "Won", "Yen", "Baht"], correctAnswerIndex: 2 },
    { question: "Singa iza no manana ny laharana atomika 1?", options: ["Hélium", "Oksizenina", "Hidrozenina", "Karbonina"], correctAnswerIndex: 2 },
    { question: "Iza no olona voalohany nandeha teny amin'ny volana?", options: ["Buzz Aldrin", "Yuri Gagarin", "Michael Collins", "Neil Armstrong"], correctAnswerIndex: 3 },
    { question: "Inona no tendrombohitra avo indrindra eran-tany?", options: ["K2", "Tendrombohitra Everest", "Kangchenjunga", "Lhotse"], correctAnswerIndex: 1 },
    { question: "Inona no fiteny fototra ampiasaina any Brezila?", options: ["Espaniola", "Portiogey", "Anglisy", "Frantsay"], correctAnswerIndex: 1 },
    { question: "Iza no ranomasina lehibe indrindra eto an-tany?", options: ["Ranomasina Atlantika", "Ranomasina Indianina", "Ranomasina Arktika", "Ranomasina Pasifika"], correctAnswerIndex: 3 },
    { question: "Firy ny fakan-toradroan'ny 64?", options: ["6", "7", "8", "9"], correctAnswerIndex: 2 },
    { question: "Iza no mpanoratra ny andian-dahatsoratra Harry Potter?", options: ["J.R.R. Tolkien", "George R.R. Martin", "J.K. Rowling", "C.S. Lewis"], correctAnswerIndex: 2 },
    { question: "Inona no anaran'ny vahindanitra misy ny rafi-masoandrontsika?", options: ["Andromeda", "Triangulum", "Whirlpool", "Milky Way"], correctAnswerIndex: 3 },
    { question: "Firy ny mpilalao ao anaty ekipa baolina kitra mahazatra eny an-kianja?", options: ["9", "10", "11", "12"], correctAnswerIndex: 2 },
    { question: "Inona no etona raisin'ny zavamaniry avy amin'ny atmosfera?", options: ["Oksizenina", "Dioksidan'ny Karbonina", "Nitrogenina", "Hidrozenina"], correctAnswerIndex: 1 },
    { question: "Mpanakanto iza no nanapaka ny sofiny?", options: ["Pablo Picasso", "Salvador Dalí", "Vincent van Gogh", "Claude Monet"], correctAnswerIndex: 2 },
    { question: "Inona ny renivohitr'i Kanada?", options: ["Toronto", "Vancouver", "Montreal", "Ottawa"], correctAnswerIndex: 3 },
    { question: "Iza no renirano lava indrindra eran-tany?", options: ["Reniranon'i Amazona", "Reniranon'i Neily", "Reniranon'i Yangtze", "Reniranon'i Mississippi"], correctAnswerIndex: 1 }
  ]
};
